name: Docker Build and Push

on:
  push:
    branches:
      - dev
    paths:
      - '.env.img'
      - 'module_based_image_builder.py'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3'

      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: List Workspace Contents
        run: |
          ls -la $GITHUB_WORKSPACE
      - name: Run Python Script
        run: python ../module_based_image_builder.py
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
